name: CI

on:
  push:
    # branches:
    #   - 'master'
  pull_request:

jobs:
  asm_test:
    name: Run integrated_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run asm test
        run: ./runner.sh test
  cargo_test:
    name: Run cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run C test
        run: ./runner.sh test_sh
