name: CI

on:
  push:
    # branches:
    #   - 'master'
  pull_request:

jobs:
  asm_test:
    name: Run integrated_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update rustup
        run: rustup self update
      - name: Build
        run: cargo build --release
      - name: run shell script tests
        run: RS9CC_ON_WORKFLOW=1 ./bin/test.sh sh
        continue-on-error: true
      - name: run C script tests
        run: RS9CC_ON_WORKFLOW=1 ./bin/test.sh
  cargo_test:
    name: Run cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update rustup
        run: rustup self update
      - name: run tests
        run: cargo test
